[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
smart_contract = "CNkCiHgVyh6u1ifYb6YpK9bZAjD7oviJEsR5G1cMmLob"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./a23QvEb6Q3adWurmUVbJ9YfAa6tiEzZBdXB8cvmhViS.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
