[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
enso_lending = "BderhzujHHQNjhCZGRjLWnN2XQ66q4EZnZx2p5WLJnBV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./a23QvEb6Q3adWurmUVbJ9YfAa6tiEzZBdXB8cvmhViS.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
