[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
enso_lending = "8kUmtqX7FazYXZTWE6vA4BCqtdqFwJ8ETkdrHtBcqVu6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/minhnguyen/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
